import Head from 'next/head';
import Cards from '../AllCards/cards';
import FirstCard from '../First-Card/first';
import Form from '../Form/form2';
import Menu from '../Menu/menu';
export default function Page({backgroundColor, color}) {
  return (
     <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
 
 <Menu />
<div>


<div>
  <FirstCard />
</div>

  <div>
    <Cards/>
  </div>

    <div>
      <Form />
    </div>
</div>
    </>
  );
}