import { Inter } from '@next/font/google';
import Head from 'next/head';
import Link from 'next/link';
import Button from '../components/Button/index';
import MonkeyCard from '../components/Card/MonkeyCard';
import monkeyDestinations from "../src/data/monkeyDestinations";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     
        
      <main className="bg-cyan-200">
      <div>
      <div className="grid bg-gray-100 lg:grid-cols-2 2xl:grid-cols-5">
        <div className="max-w-md px-8 py-12 mx-auto sm:max-w-xl lg:px-12 lg:py-24 lg:max-w-full xl:mr-0 2xl:col-span-2">
          <div className="xl:max-w-xl">
          <table> 
          <tr>
              <td>
            <img className="h-32" src="/img/monkey.gif"  alt="Monkey" />
            </td>
            <td>
            <h1 class="mt-0 text-3xl static font-semibold antialiased leading-normal">Mon<a class="text-red-500 font-extrabold">key</a> Card</h1>
            </td>
            </tr>
          </table>
            <img
              className="object-center mt-6 rounded-lg shadow-xl sm:mt-8 sm:h-64 sm:w-full sm:object-cover lg:hidden"
              src="/img/jungle.webp"
              alt="Jungle"
            />
            <h1 className="mt-6 text-2xl font-semibold tracking-tight text-gray-900 font-headline sm:mt-8 sm:text-4xl lg:text-3xl xl:text-4xl">
              Monkey <a class="text-red-500 font-extrabold">Monkey</a> Monkey
              <br className="hidden lg:inline" /> <span className="text-brand">Monkey Card</span>
            </h1>
            <p className="mt-2 text-gray-600 sm:mt-4 sm:text-xl">
            Monkeys are clever, social animals. They are known for running and leaping through trees with ease. Like apes and humans, monkeys belong to the group of mammals called primates.
            </p>
            <div className="mt-4 space-x-1 sm:mt-6">
            <Link href="https://www.crazygames.com/t/monkey" target="_blank"><Button> Click </Button></Link>
          
            </div>
          </div>
        </div>
        <div className="relative hidden lg:block 2xl:col-span-3">
          <img
            className="absolute inset-0 object-cover object-center w-full h-full"
            src="img/jungle.webp"
            alt="Jungle"
          />
        </div>
      </div>

      <div className="max-w-md px-8 py-8 mx-auto sm:max-w-xl lg:max-w-6xl lg:px-12">
        <h2 className="text-xl font-semibold text-gray-900">Monkey destinations</h2>
        <p className="mt-2 text-gray-600">Only the good monkeys</p>
        <div className="grid gap-6 mt-6 lg:grid-cols-2 xl:grid-cols-3">
          {monkeyDestinations.map((destination) => (
            <MonkeyCard {...destination}/>
          ))}
        </div> 
      </div>
    </div>
      </main>
    </>
  )
}
