import { Inter } from '@next/font/google'
import Head from 'next/head'
import Link from 'next/link'
import Button from '../components/Button/index'

const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     
        
      <main className="bg-cyan-200">
       <div className="flex flex-wrap justify-center my-11 space-between">
        <Link href="https://casapiaac.pt/" target="_blank"><Button> Botão 1 </Button></Link>
        <Link href="https://www.slbenfica.pt/" target="_blank"><Button> Botão 2 </Button></Link>
        </div>
      </main>
    </>
  )
}
